select * from customer;
-- Q1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;
--select avg(purchase_amount) from customer;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);
-- Q3. Which are the Top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
--Q4 Compare the average purchase amounts between standard and express shipping.

select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;
--Q5. Do subscribed customers spend more? Compare average spend and total revenue
--between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;
-- Q6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
--number of previous purchases , and show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	End as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type 
group by customer_segment;
